name: my first work flow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout stage
              uses: actions/checkout@v4

            - name: my first step
              run: echo "${{ vars.my_name }}"

    second-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: checkout stage
              uses: actions/checkout@v4

            - name: my first step
              run: echo "${{ secrets.MY_SUR }}"
